### ISSUE TITLE
AttributeError: 'SQLiteCredentials' object has no attribute 'host'

### ISSUE THREAD

**Issue by ChristianKranemann** [codeforkjeff/dbt-sqlite#47]
Hey 

i am using dbt-sqlit 1.4.0 with dbt-core 1.5.2 and i get the following error:

```
  File "XXX\.venv\Lib\site-packages\dbt\adapters\sqlite\connections.py", line 40, in unique_field
    return self.host
           ^^^^^^^^^
AttributeError: 'SQLiteCredentials' object has no attribute 'host'
```

The problem is the telemetry hash in SQLiteCredentials subclassing Credentials :
```
    @property
    def unique_field(self):
        """
        Hashed and included in anonymous telemetry to track adapter adoption.
        Pick a field that can uniquely identify one team/organization building with this adapter
        """
        return self.host
```

Credentials from dbt.adapters.base has no field host. Maybee change it to self.schema_directory ? 

Best Regards!

**Comment by aleenprd** [comment]
I am stuck on the same issue. :)

**Comment by zxiex** [comment]
I ran into the same issue and https://github.com/codeforkjeff/dbt-sqlite/pull/49 is my quick fix.

**Comment by tom-juntunen** [comment]
This issue has been resolved in [51](https://github.com/codeforkjeff/dbt-sqlite/pull/51).
